const keyboardLabels = {
  Backquote: {
    rus: {
      caseDown: 'ё',
      caseUp: 'Ё',
      caps: 'Ё',
      shiftCaps: 'ё',
    },
    eng: {
      caseDown: '`',
      caseUp: '~',
      caps: '~',
      shiftCaps: '`',
    },
  },
  Digit1: {
    rus: {
      caseDown: '1',
      caseUp: '!',
      caps: '1',
      shiftCaps: '!',
    },
    eng: {
      caseDown: '1',
      caseUp: '!',
      caps: '1',
      shiftCaps: '!',
    },
  },
  Digit2: {
    rus: {
      caseDown: '2',
      caseUp: '"',
      caps: '2',
      shiftCaps: '"',
    },
    eng: {
      caseDown: '2',
      caseUp: '@',
      caps: '2',
      shiftCaps: '@',
    },
  },
  Digit3: {
    rus: {
      caseDown: '3',
      caseUp: '№',
      caps: '3',
      shiftCaps: '№',
    },
    eng: {
      caseDown: '3',
      caseUp: '#',
      caps: '3',
      shiftCaps: '#',
    },
  },
  Digit4: {
    rus: {
      caseDown: '4',
      caseUp: ';',
      caps: '4',
      shiftCaps: ';',
    },
    eng: {
      caseDown: '4',
      caseUp: '$',
      caps: '4',
      shiftCaps: '$',
    },
  },
  Digit5: {
    rus: {
      caseDown: '5',
      caseUp: '%',
      caps: '5',
      shiftCaps: '%',
    },
    eng: {
      caseDown: '5',
      caseUp: '%',
      caps: '5',
      shiftCaps: '%',
    },
  },
  Digit6: {
    rus: {
      caseDown: '6',
      caseUp: ':',
      caps: '6',
      shiftCaps: ':',
    },
    eng: {
      caseDown: '6',
      caseUp: '^',
      caps: '6',
      shiftCaps: '^',
    },
  },
  Digit7: {
    rus: {
      default: '7',
      caseDown: '7',
      caseUp: '?',
      caps: '7',
      shiftCaps: '?',
      class: 'digit',
    },
    eng: {
      default: '7',
      caseDown: '7',
      caseUp: '&',
      caps: '7',
      shiftCaps: '&',
      class: 'digit',
    },
  },
  Digit8: {
    rus: {
      default: '8',
      caseDown: '8',
      caseUp: '*',
      caps: '8',
      shiftCaps: '*',
      class: 'digit',
    },
    eng: {
      default: '8',
      caseDown: '8',
      caseUp: '*',
      caps: '8',
      shiftCaps: '*',
      class: 'digit',
    },
  },
  Digit9: {
    rus: {
      default: '9',
      caseDown: '9',
      caseUp: '(',
      caps: '9',
      shiftCaps: '(',
      class: 'digit',
    },
    eng: {
      default: '9',
      caseDown: '9',
      caseUp: '(',
      caps: '9',
      shiftCaps: '(',
      class: 'digit',
    },
  },
  Digit0: {
    rus: {
      default: '0',
      caseDown: '0',
      caseUp: ')',
      caps: '0',
      shiftCaps: ')',
      class: 'digit',
    },
    eng: {
      default: '0',
      caseDown: '0',
      caseUp: ')',
      caps: '0',
      shiftCaps: ')',
      class: 'digit',
    },
  },
  Minus: {
    rus: {
      default: '-',
      caseDown: '-',
      caseUp: '_',
      caps: '-',
      shiftCaps: '_',
      class: 'minus',
    },
    eng: {
      default: '-',
      caseDown: '-',
      caseUp: '_',
      caps: '-',
      shiftCaps: '_',
      class: 'minus',
    },
  },
  Equal: {
    rus: {
      default: '=',
      caseDown: '=',
      caseUp: '+',
      caps: '=',
      shiftCaps: '+',
      class: 'equal',
    },
    eng: {
      default: '=',
      caseDown: '=',
      caseUp: '+',
      caps: '=',
      shiftCaps: '+',
      class: 'equal',
    },
  },
  Backspace: {
    rus: {
      caseDown: 'Backspace',
      caseUp: 'Backspace',
      caps: 'Backspace',
      shiftCaps: 'Backspace',
    },
    eng: {
      caseDown: 'Backspace',
      caseUp: 'Backspace',
      caps: 'Backspace',
      shiftCaps: 'Backspace',
    },
  },
  Tab: {
    rus: {
      caseDown: 'Tab',
      caseUp: 'Tab',
      caps: 'Tab',
      shiftCaps: 'Tab',
    },
    eng: {
      caseDown: 'Tab',
      caseUp: 'Tab',
      caps: 'Tab',
      shiftCaps: 'Tab',
    },
  },
  KeyQ: {
    rus: {
      value: 'й',
      caseDown: 'й',
      caseUp: 'Й',
      caps: 'Й',
      shiftCaps: 'й',
      class: 'letter',
    },
    eng: {
      value: 'q',
      caseDown: 'q',
      caseUp: 'Q',
      caps: 'Q',
      shiftCaps: 'q',
      class: 'letter',
    },
  },
  KeyW: {
    rus: {
      value: 'ц',
      caseDown: 'ц',
      caseUp: 'Ц',
      caps: 'Ц',
      shiftCaps: 'ц',
      class: 'letter',
    },
    eng: {
      default: 'w',
      caseDown: 'w',
      caseUp: 'W',
      caps: 'W',
      shiftCaps: 'w',
      class: 'letter',
    },
  },
  KeyE: {
    rus: {
      value: 'у',
      caseDown: 'у',
      caseUp: 'У',
      caps: 'У',
      shiftCaps: 'у',
      class: 'letter',
    },
    eng: {
      value: 'e',
      caseDown: 'e',
      caseUp: 'E',
      caps: 'E',
      shiftCaps: 'e',
      class: 'letter',
    },
  },
  KeyR: {
    rus: {
      default: 'к',
      caseDown: 'к',
      caseUp: 'К',
      caps: 'К',
      shiftCaps: 'к',
      class: 'letter',
    },
    eng: {
      default: 'r',
      caseDown: 'r',
      caseUp: 'R',
      caps: 'R',
      shiftCaps: 'r',
      class: 'letter',
    },
  },
  KeyT: {
    rus: {
      default: 'е',
      caseDown: 'е',
      caseUp: 'Е',
      caps: 'Е',
      shiftCaps: 'е',
      class: 'letter',
    },
    eng: {
      default: 't',
      caseDown: 't',
      caseUp: 'T',
      caps: 'T',
      shiftCaps: 't',
      class: 'letter',
    },
  },
  KeyY: {
    rus: {
      default: 'н',
      caseDown: 'н',
      caseUp: 'Н',
      caps: 'Н',
      shiftCaps: 'н',
      class: 'letter',
    },
    eng: {
      default: 'y',
      caseDown: 'y',
      caseUp: 'Y',
      caps: 'Y',
      shiftCaps: 'y',
      class: 'letter',
    },
  },
  KeyU: {
    rus: {
      default: 'г',
      caseDown: 'г',
      caseUp: 'Г',
      caps: 'Г',
      shiftCaps: 'г',
      class: 'letter',
    },
    eng: {
      default: 'u',
      caseDown: 'u',
      caseUp: 'U',
      caps: 'U',
      shiftCaps: 'u',
      class: 'letter',
    },
  },
  KeyI: {
    rus: {
      default: 'ш',
      caseDown: 'ш',
      caseUp: 'Ш',
      caps: 'Ш',
      shiftCaps: 'ш',
      class: 'letter',
    },
    eng: {
      default: 'i',
      caseDown: 'i',
      caseUp: 'I',
      caps: 'I',
      shiftCaps: 'i',
      class: 'letter',
    },
  },
  KeyO: {
    rus: {
      default: 'щ',
      caseDown: 'щ',
      caseUp: 'Щ',
      caps: 'Щ',
      shiftCaps: 'щ',
      class: 'letter',
    },
    eng: {
      default: 'o',
      caseDown: 'o',
      caseUp: 'O',
      caps: 'O',
      shiftCaps: 'o',
      class: 'letter',
    },
  },
  KeyP: {
    rus: {
      default: 'з',
      caseDown: 'з',
      caseUp: 'З',
      caps: 'З',
      shiftCaps: 'з',
      class: 'letter',
    },
    eng: {
      default: 'p',
      caseDown: 'p',
      caseUp: 'P',
      caps: 'P',
      shiftCaps: 'p',
      class: 'letter',
    },
  },
  BracketLeft: {
    rus: {
      default: 'х',
      caseDown: 'х',
      caseUp: 'Х',
      caps: 'Х',
      shiftCaps: 'х',
      class: 'symbol',
    },
    eng: {
      default: '[',
      caseDown: '[',
      caseUp: '{',
      caps: '[',
      shiftCaps: '{',
      class: 'symbol',
    },
  },
  BracketRight: {
    rus: {
      default: 'ъ',
      caseDown: 'ъ',
      caseUp: 'Ъ',
      caps: 'Ъ',
      shiftCaps: 'ъ',
      class: 'symbol',
    },
    eng: {
      default: ']',
      caseDown: ']',
      caseUp: '}',
      caps: ']',
      shiftCaps: '}',
      class: 'symbol',
    },
  },
  Backslash: {
    rus: {
      default: '\\',
      caseDown: '\\',
      caseUp: '/',
      caps: '\\',
      shiftCaps: '/',
      class: 'symbol',
    },
    eng: {
      default: '\\',
      caseDown: '\\',
      caseUp: '|',
      caps: '\\',
      shiftCaps: '|',
      class: 'symbol',
    },
  },
  Delete: {
    rus: {
      default: 'Backspace',
      caseDown: 'Backspace',
      caseUp: 'Backspace',
      caps: 'Backspace',
      shiftCaps: 'Backspace',
      class: 'Backspace',
    },
    eng: {
      default: 'Delete',
      caseDown: 'Delete',
      caseUp: 'Delete',
      caps: 'Delete',
      shiftCaps: 'Delete',
      class: 'Delete',
    },
  },
  CapsLock: {
    rus: {
      default: 'CapsLock',
      caseDown: 'CapsLock',
      caseUp: 'CapsLock',
      caps: 'CapsLock',
      shiftCaps: 'CapsLock',
      class: 'capslock',
    },
    eng: {
      default: 'CapsLock',
      caseDown: 'CapsLock',
      caseUp: 'CapsLock',
      caps: 'CapsLock',
      shiftCaps: 'CapsLock',
      class: 'capslock',
    },
  },
  KeyA: {
    rus: {
      default: 'ф',
      caseDown: 'ф',
      caseUp: 'Ф',
      caps: 'Ф',
      shiftCaps: 'ф',
      class: 'letter',
    },
    eng: {
      default: 'a',
      caseDown: 'a',
      caseUp: 'A',
      caps: 'A',
      shiftCaps: 'a',
      class: 'letter',
    },
  },
  KeyS: {
    rus: {
      default: 'ы',
      caseDown: 'ы',
      caseUp: 'Ы',
      caps: 'Ы',
      shiftCaps: 'ы',
      class: 'letter',
    },
    eng: {
      default: 's',
      caseDown: 's',
      caseUp: 'S',
      caps: 'S',
      shiftCaps: 's',
      class: 'letter',
    },
  },
  KeyD: {
    rus: {
      default: 'в',
      caseDown: 'в',
      caseUp: 'В',
      caps: 'В',
      shiftCaps: 'в',
      class: 'letter',
    },
    eng: {
      default: 'd',
      caseDown: 'd',
      caseUp: 'D',
      caps: 'D',
      shiftCaps: 'd',
      class: 'letter',
    },
  },
  KeyF: {
    rus: {
      default: 'а',
      caseDown: 'а',
      caseUp: 'А',
      caps: 'А',
      shiftCaps: 'а',
      class: 'letter',
    },
    eng: {
      default: 'f',
      caseDown: 'f',
      caseUp: 'F',
      caps: 'F',
      shiftCaps: 'f',
      class: 'letter',
    },
  },
  KeyG: {
    rus: {
      default: 'п',
      caseDown: 'п',
      caseUp: 'П',
      caps: 'П',
      shiftCaps: 'п',
      class: 'letter',
    },
    eng: {
      default: 'g',
      caseDown: 'g',
      caseUp: 'G',
      caps: 'G',
      shiftCaps: 'g',
      class: 'letter',
    },
  },
  KeyH: {
    rus: {
      default: 'р',
      caseDown: 'р',
      caseUp: 'Р',
      caps: 'Р',
      shiftCaps: 'р',
      class: 'letter',
    },
    eng: {
      default: 'h',
      caseDown: 'h',
      caseUp: 'H',
      caps: 'H',
      shiftCaps: 'h',
      class: 'letter',
    },
  },
  KeyJ: {
    rus: {
      default: 'о',
      caseDown: 'о',
      caseUp: 'О',
      caps: 'О',
      shiftCaps: 'о',
      class: 'letter',
    },
    eng: {
      default: 'j',
      caseDown: 'j',
      caseUp: 'J',
      caps: 'J',
      shiftCaps: 'j',
      class: 'letter',
    },
  },
  KeyK: {
    rus: {
      default: 'л',
      caseDown: 'л',
      caseUp: 'Л',
      caps: 'Л',
      shiftCaps: 'л',
      class: 'letter',
    },
    eng: {
      default: 'k',
      caseDown: 'k',
      caseUp: 'K',
      caps: 'K',
      shiftCaps: 'k',
      class: 'letter',
    },
  },
  KeyL: {
    rus: {
      default: 'д',
      caseDown: 'д',
      caseUp: 'Д',
      caps: 'Д',
      shiftCaps: 'д',
      class: 'letter',
    },
    eng: {
      default: 'l',
      caseDown: 'l',
      caseUp: 'L',
      caps: 'L',
      shiftCaps: 'l',
      class: 'letter',
    },
  },
  Semicolon: {
    rus: {
      default: 'ж',
      caseDown: 'ж',
      caseUp: 'Ж',
      caps: 'Ж',
      shiftCaps: 'ж',
      class: 'letter',
    },
    eng: {
      default: ';',
      caseDown: ';',
      caseUp: ':',
      caps: ';',
      shiftCaps: ':',
      class: 'letter',
    },
  },
  Quote: {
    rus: {
      default: 'э',
      caseDown: 'э',
      caseUp: 'Э',
      caps: 'Э',
      shiftCaps: 'э',
      class: 'letter',
    },
    eng: {
      default: '\'',
      caseDown: '\'',
      caseUp: '"',
      caps: '\'',
      shiftCaps: '"',
      class: 'letter',
    },
  },
  Enter: {
    rus: {
      default: 'Enter',
      caseDown: 'Enter',
      caseUp: 'Enter',
      caps: 'Enter',
      shiftCaps: 'Enter',
      class: 'enter',
    },
    eng: {
      default: 'Enter',
      caseDown: 'Enter',
      caseUp: 'Enter',
      caps: 'Enter',
      shiftCaps: 'Enter',
      class: 'enter',
    },
  },
  ShiftLeft: {
    rus: {
      default: 'Shift',
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      class: 'functional',
    },
    eng: {
      default: 'Shift',
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      class: 'functional',
    },
  },
  KeyZ: {
    rus: {
      default: 'я',
      caseDown: 'я',
      caseUp: 'Я',
      caps: 'Я',
      shiftCaps: 'я',
      class: 'letter',
    },
    eng: {
      default: 'z',
      caseDown: 'z',
      caseUp: 'Z',
      caps: 'Z',
      shiftCaps: 'z',
      class: 'letter',
    },
  },
  KeyX: {
    rus: {
      default: 'ч',
      caseDown: 'ч',
      caseUp: 'Ч',
      caps: 'Ч',
      shiftCaps: 'ч',
      class: 'letter',
    },
    eng: {
      default: 'x',
      caseDown: 'x',
      caseUp: 'X',
      caps: 'X',
      shiftCaps: 'x',
      class: 'letter',
    },
  },
  KeyC: {
    rus: {
      default: 'с',
      caseDown: 'с',
      caseUp: 'С',
      caps: 'С',
      shiftCaps: 'с',
      class: 'letter',
    },
    eng: {
      default: 'c',
      caseDown: 'c',
      caseUp: 'C',
      caps: 'C',
      shiftCaps: 'c',
      class: 'letter',
    },
  },
  KeyV: {
    rus: {
      default: 'м',
      caseDown: 'м',
      caseUp: 'М',
      caps: 'М',
      shiftCaps: 'м',
      class: 'letter',
    },
    eng: {
      default: 'v',
      caseDown: 'v',
      caseUp: 'V',
      caps: 'V',
      shiftCaps: 'v',
      class: 'letter',
    },
  },
  KeyB: {
    rus: {
      default: 'и',
      caseDown: 'и',
      caseUp: 'И',
      caps: 'И',
      shiftCaps: 'и',
      class: 'letter',
    },
    eng: {
      default: 'b',
      caseDown: 'b',
      caseUp: 'B',
      caps: 'B',
      shiftCaps: 'b',
      class: 'letter',
    },
  },
  KeyN: {
    rus: {
      default: 'т',
      caseDown: 'т',
      caseUp: 'Т',
      caps: 'Т',
      shiftCaps: 'т',
      class: 'letter',
    },
    eng: {
      default: 'n',
      caseDown: 'n',
      caseUp: 'N',
      caps: 'N',
      shiftCaps: 'n',
      class: 'letter',
    },
  },
  KeyM: {
    rus: {
      default: 'ь',
      caseDown: 'ь',
      caseUp: 'Ь',
      caps: 'Ь',
      shiftCaps: 'ь',
      class: 'letter',
    },
    eng: {
      default: 'm',
      caseDown: 'm',
      caseUp: 'M',
      caps: 'M',
      shiftCaps: 'm',
      class: 'letter',
    },
  },
  Comma: {
    rus: {
      default: 'б',
      caseDown: 'б',
      caseUp: 'Б',
      caps: 'Б',
      shiftCaps: 'б',
      class: 'symbol',
    },
    eng: {
      default: ',',
      caseDown: ',',
      caseUp: '<',
      caps: ',',
      shiftCaps: '<',
      class: 'symbol',
    },
  },
  Period: {
    rus: {
      default: 'ю',
      caseDown: 'ю',
      caseUp: 'Ю',
      caps: 'Ю',
      shiftCaps: 'ю',
      class: 'symbol',
    },
    eng: {
      default: '.',
      caseDown: '.',
      caseUp: '>',
      caps: '.',
      shiftCaps: '>',
      class: 'symbol',
    },
  },
  Slash: {
    rus: {
      default: '.',
      caseDown: '.',
      caseUp: ',',
      caps: '.',
      shiftCaps: ',',
      class: 'symbol',
    },
    eng: {
      default: '/',
      caseDown: '/',
      caseUp: '?',
      caps: '/',
      shiftCaps: '?',
      class: 'symbol',
    },
  },
  ArrowUp: {
    rus: {
      default: '↑',
      caseDown: '↑',
      caseUp: '↑',
      caps: '↑',
      shiftCaps: '↑',
      class: 'symbol',
    },
    eng: {
      default: '↑',
      caseDown: '↑',
      caseUp: '↑',
      caps: '↑',
      shiftCaps: '↑',
      class: 'symbol',
    },
  },
  ShiftRight: {
    rus: {
      default: 'Shift',
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      class: 'symbol',
    },
    eng: {
      default: 'Shift',
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      class: 'symbol',
    },
  },
  ControlLeft: {
    rus: {
      caseDown: 'Ctrl',
      caseUp: 'Ctrl',
      caps: 'Ctrl',
      shiftCaps: 'Ctrl',
    },
    eng: {
      caseDown: 'Ctrl',
      caseUp: 'Ctrl',
      caps: 'Ctrl',
      shiftCaps: 'Ctrl',
    },
  },
  MetaLeft: {
    rus: {
      caseDown: 'Win',
      caseUp: 'Win',
      caps: 'Win',
      shiftCaps: 'Win',
    },
    eng: {
      caseDown: 'Win',
      caseUp: 'Win',
      caps: 'Win',
      shiftCaps: 'Win',
    },
  },
  AltLeft: {
    rus: {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
    },
    eng: {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
    },
  },
  Space: {
    rus: {
      caseDown: ' ',
      caseUp: ' ',
      caps: ' ',
      shiftCaps: ' ',
    },
    eng: {
      caseDown: ' ',
      caseUp: ' ',
      caps: ' ',
      shiftCaps: ' ',
    },
  },
  AltRight: {
    rus: {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
    },
    eng: {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
    },
  },
  ArrowLeft: {
    rus: {
      caseDown: '←',
      caseUp: '←',
      caps: '←',
      shiftCaps: '←',
    },
    eng: {
      caseDown: '←',
      caseUp: '←',
      caps: '←',
      shiftCaps: '←',
    },
  },
  ArrowDown: {
    rus: {
      caseDown: '↓',
      caseUp: '↓',
      caps: '↓',
      shiftCaps: '↓',
    },
    eng: {
      caseDown: '↓',
      caseUp: '↓',
      caps: '↓',
      shiftCaps: '↓',
    },
  },
  ArrowRight: {
    rus: {
      caseDown: '→',
      caseUp: '→',
      caps: '→',
      shiftCaps: '→',
    },
    eng: {
      caseDown: '→',
      caseUp: '→',
      caps: '→',
      shiftCaps: '→',
    },
  },
  ControlRight: {
    rus: {
      caseDown: 'Ctrl',
      caseUp: 'Ctrl',
      caps: 'Ctrl',
      shiftCaps: 'Ctrl',
    },
    eng: {
      caseDown: 'Ctrl',
      caseUp: 'Ctrl',
      caps: 'Ctrl',
      shiftCaps: 'Ctrl',
    },
  },
};

export default keyboardLabels;
